export const REQUEST_MSG_CREATE_DONE = 'REQUEST_MSG_CREATE_DONE'
export const REQUEST_MSG_CREATE_FAIL = 'REQUEST_MSG_CREATE_FAIL'

export const WS_MSG_CREATE_DONE = 'WS_MSG_CREATE_DONE'
export const WS_MSG_UPDATE_DONE = 'WS_MSG_UPDATE_DONE'
export const WS_START_MESSAGING = 'WS_START_MESSAGING'

export const UPDATE_LOST_MSG = 'UPDATE_LOST_MSG'

export const REQUEST_MSG_READ_DONE = 'REQUEST_MSG_READ_DONE'
export const REQUEST_MSG_READ_FAIL = 'REQUEST_MSG_READ_FAIL'

export const TRANSPORT_SOCKET = 'socket'
export const TRANSPORT_HTTP = 'http'
